# Generated by Django 5.1.12 on 2025-10-22 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='battery',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='information',
            name='byteMV',
            field=models.FloatField(default=2800.0),
        ),
        migrations.AddField(
            model_name='information',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
